### ISSUE TITLE
Start with a Docker..

### ISSUE THREAD

**Issue by anarro** [githubcdr/docker-mycontroller#2]
Hi,

My name is Antoni and I'm not familiarized working with the Docker's platform..

I have a Synology NAS with a Docker process and your docker-mycontroller package but I don't know how to change the "mycontroller.properties" file and others settings, etc..

Is it possible to need something like?:

docker run -d -p 1883 -p 8443 --name mycontroller cdrocker/mycontroller -v <path_to_config>:/conf -v <path_to_temp>:/temp ???

Could you help me, please?

Best regards.
Antoni.

**Comment by githubcdr** [comment]
Hi,

You are right, use the volume mapping in docker with -v, I believe you can even map a single file with this function.

Should be easy to debug with docker logs -f <containerid>

Good luck!

reference: https://docs.docker.com/engine/tutorials/dockervolumes/
